[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*.dc.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/support.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/image-slot.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
